fix: add Rydberg local schemas
amazon-braket/amazon-braket-schemas-python pull request #176
Opened 2024-04-11 19:19 UTC by math411

*Issue #, if available:*

*Description of changes:*

*Testing done:*

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [ ] I have read the [CONTRIBUTING](https://github.com/amazon-braket/amazon-braket-schemas-python/blob/main/CONTRIBUTING.md) doc
- [ ] I used the commit message format described in [CONTRIBUTING](https://github.com/amazon-braket/amazon-braket-schemas-python/blob/main/CONTRIBUTING.md#commit-your-change)
- [ ] I have updated any necessary documentation, including [READMEs](https://github.com/amazon-braket/amazon-braket-schemas-python/blob/main/README.md) and [API docs](https://github.com/amazon-braket/amazon-braket-schemas-python/blob/main/CONTRIBUTING.md#documentation-guidelines) (if appropriate)

#### Tests

- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have checked that my tests are not configured for a specific region or account (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-04-11 19:32 UTC, rchilaka-amzn requested changes

2024-04-11 19:32 UTC, rchilaka-amzn commented on src/braket/ir/ahs/__init__.py
> +from braket.ir.ahs.shifting_field import LocalDetuning  # noqa: F401
local_detuning, not shifting_field

2024-04-11 19:32 UTC, rchilaka-amzn commented on src/braket/device_schema/quera/quera_ahs_paradigm_properties_v1.py
> +    Constraints for the parameters of the local shifting field
Not shifting field. Local detuning.

2024-04-11 19:32 UTC, rchilaka-amzn commented on src/braket/device_schema/quera/quera_ahs_paradigm_properties_v1.py
> +    Performance metrics for the local shifting field
Local detuning field

2024-04-11 19:36 UTC, math411 commented on src/braket/ir/ahs/__init__.py
> +from braket.ir.ahs.shifting_field import LocalDetuning  # noqa: F401
Fixed

2024-04-11 19:36 UTC, math411 commented on src/braket/device_schema/quera/quera_ahs_paradigm_properties_v1.py
> +    Performance metrics for the local shifting field
Fixed

2024-04-11 19:49 UTC, rchilaka-amzn commented on src/braket/device_schema/quera/quera_ahs_paradigm_properties_v1.py
> +        detuningErrorRms(Decimal):
nvm, these look fine. Sorry!

2024-04-12 21:05 UTC, maolinml approved these changes

2024-04-12 22:18 UTC, rchilaka-amzn approved these changes

2024-04-12 23:15 UTC, speller26 approved these changes

2024-04-12 23:16 UTC, merged